// common.shader
// generated by ShaderCleaner on Thu Feb  6 12:43:32 2003
// 80 total shaders

textures/common/ai_nopass
{
	qer_trans 0.30
	surfaceparm ai_nopass
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/ai_nopasslarge
{
	qer_trans 0.30
	surfaceparm ai_nopasslarge
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/ai_nosight
{
	qer_trans 0.3
	surfaceparm ai_nosight
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/ai_nosight_shoot_through
{
	qer_trans 0.3
	surfaceparm ai_nosight
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/antiportal
{
	qer_nocarve
	qer_trans 0.30
	surfaceparm antiportal
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm structural
	surfaceparm trans
}

textures/common/areaportal
{
	surfaceparm areaportal
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm structural
	surfaceparm trans
}

textures/common/caulk
{
	surfaceparm nodraw
	surfaceparm nomarks
}

textures/common/caulkterrain
{
	qer_editorimage textures/common/caulk.tga
	surfaceparm nodraw
	surfaceparm nomarks
}

textures/common/clip
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/clip_metal
{
	qer_trans 0.3
	surfaceparm clipmissile
	surfaceparm metalsteps
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/clipfull
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/clipmissile
{
	qer_trans 0.3
	surfaceparm clipmissile
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/clipmonster
{
	qer_trans 0.3
	surfaceparm monsterclip
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/clipmonster2
{
	qer_editorimage textures/common/clipmonster.tga
	surfaceparm monsterclip
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/clipshot
{
	qer_trans 0.3
	surfaceparm clipshot
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/clipweap
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
}

textures/common/clipweap_metal
{
	qer_editorimage textures/common/clipweapmetal.tga
	qer_trans 0.3
	surfaceparm metalsteps
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
}

// Don't ask...
textures/common/clipweapmetal
{
	qer_editorimage "textures/common/clip_metal.tga"
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm metalsteps
}

textures/common/clipweap_wood
{
	qer_editorimage textures/common/clipweapwood.tga
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/clusterportal
{
	qer_trans 0.3
	surfaceparm clusterportal
	surfaceparm detail
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/cushion
{
	qer_nocarve
	qer_trans 0.5
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
}

textures/common/hint
{
	qer_nocarve
	qer_trans 0.3
	surfaceparm hint
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm structural
	surfaceparm trans
}

textures/common/ladder
{
	qer_trans 0.3
	surfaceparm ladder
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/lightgrid
{
	qer_trans 0.5
	surfaceparm detail
	surfaceparm lightgrid
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/lmterrain_sand_marks
{
	qer_editorimage textures/common/terrain_sand.tga
	q3map_shadeangle 45
	q3map_terrain
	surfaceparm gravelsteps
	surfaceparm nodraw
}

textures/common/lmterrain_snow_marks
{
	qer_editorimage textures/common/terrain_snow.tga
	q3map_shadeangle 90
	q3map_terrain
	surfaceparm nodraw
	surfaceparm snowsteps
}

textures/common/nodraw
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/nodrawnonsolid
{
	surfaceparm nodraw
	surfaceparm nonsolid
}

textures/common/nodrawwater
{
	qer_trans .5
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm water
}

textures/common/nodrawslag
{
	qer_trans .5
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm slag
}

textures/common/nodrop
{
	qer_nocarve
	qer_trans 0.5
	cull disable
	surfaceparm nodraw
	surfaceparm nodrop
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm nonsolid
	surfaceparm trans
}

textures/common/origin
{
	qer_nocarve
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm origin
	surfaceparm trans
}

textures/common/skip
{
	qer_nocarve
	qer_trans 0.30
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm skip
	surfaceparm structural
	surfaceparm trans
}

textures/common/slick
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm slick
	surfaceparm trans
}

textures/common/terrain
{
	q3map_terrain
	surfaceparm grasssteps
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
}

textures/common/terrain_snow
{
	q3map_terrain
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
//	surfaceparm snow
	surfaceparm snowsteps
}

textures/common/terrain_snow_wils
{
	q3map_terrain
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
	surfaceparm snowsteps
}

textures/common/terrain2
{
	q3map_terrain
//	surfaceparm dust
	surfaceparm grasssteps
	surfaceparm nodraw
	surfaceparm nolightmap
	surfaceparm nomarks
}

textures/common/trigger
{
	qer_nocarve
	qer_trans 0.5
	surfaceparm nodraw
	surfaceparm trans
}

// exactly like caulk, just a different image so you can tell the difference
textures/common/hullcaulk
{
	surfaceparm nodraw
	surfaceparm nomarks
}

// hint with normal priority.
textures/common/subtlehint
{
	qer_nocarve
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm structural
	surfaceparm trans
}

// exactly like skip, but it filters with hint
textures/common/hintskip
{
	qer_editorimage textures/common/skip
	qer_nocarve
	qer_trans 0.30
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm skip
	surfaceparm structural
	surfaceparm trans
}


//ETJump mapping extras


//General useful shaders

textures/common/slickcushion
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm slick
	surfaceparm trans
	surfaceparm nodamage
}

textures/common/nonoclip
{
	qer_nocarve
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm donotenterlarge
}

textures/common/nosave
{
	qer_nocarve
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm clusterportal
}

textures/common/nodelay
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm monsterslicknorth
}

textures/common/noprone
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm donotenter
}


//Cushion shaders with different footsteps

textures/common/cushion_metal
{
	qer_nocarve
	qer_trans 0.5
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm metalsteps
}

textures/common/cushion_wood
{
	qer_nocarve
	qer_trans 0.5
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm woodsteps
}

textures/common/cushion_grass
{
	qer_nocarve
	qer_trans 0.5
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm grasssteps
}

textures/common/cushion_gravel
{
	qer_nocarve
	qer_trans 0.5
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm gravelsteps
}

textures/common/cushion_snow
{
	qer_nocarve
	qer_trans 0.5
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm snowsteps
}

textures/common/cushion_roof
{
	qer_nocarve
	qer_trans 0.5
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm roofsteps
}

textures/common/cushion_carpet
{
	qer_nocarve
	qer_trans 0.5
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm carpetsteps
}

textures/common/cushion_splash
{
	qer_nocarve
	qer_trans 0.5
	surfaceparm nodamage
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
	surfaceparm splash
}


// Extra clip brushes

textures/common/clip_metal2		// Without clipmissile
{
	qer_editorImage textures/common/clip_metal_proper.tga
	qer_trans 0.3
	surfaceparm metalsteps
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm playerclip
	surfaceparm trans
}

textures/common/clipweap_glass
{
	qer_editorImage textures/common/clipweapglass.tga
	qer_trans 0.3
	surfaceparm glass
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
}

textures/common/clipweap_carpet
{
	qer_editorImage textures/common/clipweapcarpet.tga
	qer_trans 0.3
	surfaceparm carpetsteps
	surfaceparm nodraw
	surfaceparm nomarks
	surfaceparm trans
}


//Portalsurfaces

textures/common/portalsurface
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm monsterslickeast
}

textures/common/portalsurface_slick
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm slick
	surfaceparm monsterslickeast
}

textures/common/portalsurface_cushion
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm nodamage
	surfaceparm monsterslickeast
}

textures/common/portalsurface_slickcushion
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm slick
	surfaceparm nodamage
	surfaceparm monsterslickeast
}

// NOTE: this requires compilation with '-custinfoparms' switch in BSP stage,
// and for 'custinfoparms.txt' to be present in the 'scripts' directory
textures/common/portalclip
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	surfaceparm portalclip
}

//Overbounce surfaces

textures/common/overbounce
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm monsterslicksouth
}

textures/common/overbounce_slick
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm slick
	surfaceparm monsterslicksouth
}

textures/common/overbounce_cushion
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm nodamage
	surfaceparm monsterslicksouth
}

textures/common/overbounce_slickcushion
{
	qer_trans 0.3
	surfaceparm nodraw
	surfaceparm trans
	surfaceparm slick
	surfaceparm nodamage
	surfaceparm monsterslicksouth
}


//AlphaMod Shaders

textures/common/alpha_000		//Only primary texture
{
	q3map_alphaMod volume
	q3map_alphaMod set 0.0
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	qer_trans 0.3
	qer_noCarve
}

textures/common/alpha_025
{
	q3map_alphaMod volume
	q3map_alphaMod set 0.25
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	qer_trans 0.3
	qer_noCarve
}

textures/common/alpha_050
{
	q3map_alphaMod volume
	q3map_alphaMod set 0.50
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	qer_trans 0.3
	qer_noCarve
}

textures/common/alpha_065
{
	q3map_alphaMod volume
	q3map_alphaMod set 0.65
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	qer_trans 0.3
	qer_noCarve
}

textures/common/alpha_075
{
	q3map_alphaMod volume
	q3map_alphaMod set 0.75
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	qer_trans 0.3
	qer_noCarve
}

textures/common/alpha_085
{
	q3map_alphaMod volume
	q3map_alphaMod set 0.85
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	qer_trans 0.3
	qer_noCarve
}

textures/common/alpha_100		//Only secondary texture
{
	q3map_alphaMod volume
	q3map_alphaMod set 1.0
	surfaceparm nodraw
	surfaceparm nonsolid
	surfaceparm trans
	qer_trans 0.3
	qer_noCarve
}
